import { describe, expect, test } from "bun:test";
import { GlobalWindow } from "happy-dom";
import {
  __captchaMemStats,
  createDom,
  destroyDom,
  installGlobalWindowAlias,
  noteRequest,
  reclaimCaptchaHeap,
  rememberCdnBody,
  removeGlobalWindowAlias,
} from "./captcha-happy.js";

// The guest-timer contract, stated behaviourally: a timer armed by guest code
// MUST stop firing once its window is destroyed, and the host's own timers
// MUST keep the Node ref/unref contract throughout. Both were violated by the
// stack-sniffing dispatcher this replaced — in opposite directions.
describe("guest timer ownership (lexical scope)", () => {
  const EVALUATE_SCRIPT = "Symbol(evaluateScript)";
  const GUEST_URL = "https://g.alicdn.com/captcha-frontend/FeiLin/1.5.1/feilin008.js";

  function evaluateScriptSymbol(w: object): symbol | undefined {
    for (const target of [w, Object.getPrototypeOf(w)]) {
      const found = Object.getOwnPropertySymbols(target ?? {}).find(
        (s) => String(s) === EVALUATE_SCRIPT,
      );
      if (found) return found;
    }
    return undefined;
  }

  /**
   * Arm a repeating timer from guest source, destroy the window, and report
   * how many times the callback fired before and after. `after > 0` means the
   * timer escaped onto the host lane and is now immortal.
   *
   * Real timers are the subject under test, not incidental latency: the whole
   * question is whether happy-dom's registry cancels these handles at
   * `close()`. Faking the clock would replace the very mechanism being
   * verified. Waits are condition-driven (first tick / quiet period) rather
   * than fixed guesses.
   */
  async function ticksAcrossTeardown(guestSource: string): Promise<{ before: number; after: number }> {
    const dom = await createDom("sgp", "no8xfe");
    const w = dom.window as unknown as Record<string | symbol, unknown>;
    let ticks = 0;
    (globalThis as Record<string, unknown>).__capTestTick = () => { ticks++; };
    try {
      const sym = evaluateScriptSymbol(w);
      if (!sym) throw new Error("happy-dom build exposes no evaluateScript symbol");
      (w[sym] as (code: string, options: unknown) => unknown)(guestSource, { filename: GUEST_URL });
      // Wait for the heartbeat to prove it is live, not for a fixed duration.
      const deadline = Date.now() + 5_000;
      while (ticks === 0 && Date.now() < deadline) await Bun.sleep(10);
      const before = ticks;
      destroyDom(w);
      // A cancelled interval produces no further ticks; give it several
      // periods of the 40ms heartbeat to prove silence.
      await Bun.sleep(300);
      return { before, after: ticks - before };
    } finally {
      try { clearInterval((globalThis as Record<string, unknown>).__capTestArmed as never); } catch {}
      delete (globalThis as Record<string, unknown>).__capTestTick;
      delete (globalThis as Record<string, unknown>).__capTestArmed;
    }
  }

  const ARM = "globalThis.__capTestArmed =";
  const TICK = "globalThis.__capTestTick";

  // Each row is a distinct way guest code reaches `setInterval`. The
  // `new Function` rows are the ones a stack-based router cannot see: the
  // generated frame carries no CDN source URL, so its heartbeat used to be
  // armed on the immortal host lane and outlived the window — the field
  // crash "ReferenceError: moveBy is not defined" from feilin008.js's `tE`.
  const GUEST_ENTRY_POINTS: Record<string, string> = {
    "direct call": `${ARM} setInterval(${TICK}, 40);`,
    "generated by new Function": `${ARM} (new Function("t","return setInterval(t,40);"))(${TICK});`,
    "generated without new": `${ARM} Function("t","return setInterval(t,40);")(${TICK});`,
    "generated two levels deep": `${ARM} (new Function("t","return (new Function('u','return setInterval(u,40);'))(t);"))(${TICK});`,
    "returned from eval": `${ARM} eval("(function(t){ return setInterval(t,40); })")(${TICK});`,
  };

  for (const [label, source] of Object.entries(GUEST_ENTRY_POINTS)) {
    test(`a heartbeat armed via ${label} dies with the window`, async () => {
      const { before, after } = await ticksAcrossTeardown(source);
      expect(before).toBeGreaterThan(0); // the timer really was running
      expect(after).toBe(0);
    }, 20_000);
  }

  test("guest top-level declarations still reach the global object", async () => {
    // The scope is applied with `with`, not an IIFE, precisely so that guest
    // `var`/`function` declarations keep escaping. Wrapping in a function
    // swallowed them and `initAliyunCaptcha` never appeared — every solve
    // then timed out waiting for it.
    const dom = await createDom("sgp", "no8xfe");
    const w = dom.window as unknown as Record<string | symbol, unknown>;
    try {
      const sym = evaluateScriptSymbol(w)!;
      (w[sym] as (code: string, options: unknown) => unknown)(
        "function __capTestTopLevel(){ return 'visible'; } var __capTestVar = 7;",
        { filename: GUEST_URL },
      );
      const g = globalThis as Record<string, unknown>;
      expect(typeof g.__capTestTopLevel).toBe("function");
      expect(g.__capTestVar).toBe(7);
    } finally {
      destroyDom(w);
      delete (globalThis as Record<string, unknown>).__capTestTopLevel;
      delete (globalThis as Record<string, unknown>).__capTestVar;
    }
  }, 20_000);
});

describe("host timer contract during a solve", () => {
  test("globalThis timers stay pristine while a window is aliased", async () => {
    // Bun internals (node:_http_server keep-alive, undici, AbortSignal.timeout)
    // arm timers through the bare global and call `.unref()` on the result.
    // The previous dispatcher handed them a window timer whenever a guest frame
    // happened to sit on the stack, producing
    // "TypeError: setTimeout(...).unref is not a function" — a proxy-wide crash.
    const pristine = globalThis.setTimeout;
    const w = new GlobalWindow({
      url: "https://zcode.z.ai/",
      settings: { suppressInsecureJavaScriptEnvironmentWarning: true },
    });
    installGlobalWindowAlias(globalThis, w, 20);
    try {
      expect(globalThis.setTimeout).toBe(pristine);
      const handle = setTimeout(() => {}, 0);
      expect(typeof handle.unref).toBe("function");
      handle.unref();
      clearTimeout(handle);
      const signal = AbortSignal.timeout(50);
      expect(signal.aborted).toBe(false);
    } finally {
      await w.happyDOM.close();
      removeGlobalWindowAlias(globalThis, w);
      await Bun.sleep(60);
    }
  });
});

describe("alias lifecycle (install/remove descriptor contract)", () => {
  const TIMER_PROPS = ["setTimeout", "setInterval", "clearTimeout", "clearInterval"];

  function makeSandbox() {
    const g: Record<string, unknown> = {};
    const pristine = { marker: "pristine-host-timer" };
    for (const p of TIMER_PROPS) g[p] = () => pristine;
    // Host-existing globals the window also exposes: the generic alias loop
    // overwrites these, so teardown must put the host versions back.
    // client-signing.ts:100/:115 calls bare `atob`/`btoa` between solves.
    const hostAtob = (s: string) => `host-atob(${s})`;
    g.atob = hostAtob;
    g.btoa = (s: string) => `host-btoa(${s})`;
    // A HOST getter-typed global (Bun's navigator/self are accessors) — the
    // tombstone must never grace-delete it after the restore, even though a
    // restored getter passes the `d?.get` re-check.
    const hostNavigator = { userAgent: "host" };
    Object.defineProperty(g, "navigator", { get: () => hostNavigator, configurable: true });
    const w: Record<string, unknown> = {
      setTimeout: () => 0,
      setInterval: () => 0,
      clearTimeout: () => {},
      clearInterval: () => {},
      Text: class FakeText {},
      atob: (s: string) => `win-atob(${s})`,
      btoa: (s: string) => `win-btoa(${s})`,
      navigator: { userAgent: "window" },
    };
    return { g, w, pristine, hostNavigator };
  }

  test("the alias never touches the host timers", () => {
    const { g, w, pristine } = makeSandbox();
    const before = Object.fromEntries(
      TIMER_PROPS.map((p) => [p, Object.getOwnPropertyDescriptor(g, p)]),
    );
    installGlobalWindowAlias(g, w);
    try {
      // Bun's runtime resolves these by bare identifier and unrefs the result.
      // Aliasing them onto the window is what produced
      // "setTimeout(...).unref is not a function" in the field.
      for (const p of TIMER_PROPS) {
        expect(Object.getOwnPropertyDescriptor(g, p)).toEqual(before[p]);
      }
      expect((g.setTimeout as () => unknown)()).toBe(pristine);
    } finally {
      removeGlobalWindowAlias(g, w);
    }
  });

  test("host-existing globals are served from the window during a solve and restored after", () => {
    const { g, w } = makeSandbox();
    installGlobalWindowAlias(g, w);
    expect((g.atob as (s: string) => string)("x")).toBe("win-atob(x)");
    removeGlobalWindowAlias(g, w);
    // A hard delete here left client-signing's bare `btoa`/`atob` as
    // ReferenceErrors — the field-reported failure this restore prevents.
    expect(Object.getOwnPropertyDescriptor(g, "atob")?.get).toBeUndefined();
    expect((g.atob as (s: string) => string)("y")).toBe("host-atob(y)");
    expect((g.btoa as (s: string) => string)("y")).toBe("host-btoa(y)");
  });

  test("concurrent installs restore exactly once, on the last remove", () => {
    const { g } = makeSandbox();
    const w1: Record<string, unknown> = { atob: (s: string) => `w1(${s})` };
    const w2: Record<string, unknown> = { atob: (s: string) => `w2(${s})` };
    const orig = g.atob;
    installGlobalWindowAlias(g, w1);
    installGlobalWindowAlias(g, w2);
    removeGlobalWindowAlias(g, w1); // refcount 2→1: no restore yet
    expect(g.atob).not.toBe(orig);
    removeGlobalWindowAlias(g, w2); // refcount 1→0: restore
    expect(g.atob).toBe(orig);
  });

  test("window-sourced globals stay resolvable through the post-teardown grace period", async () => {
    const { g, w, hostNavigator } = makeSandbox();
    installGlobalWindowAlias(g, w, 15);
    removeGlobalWindowAlias(g, w);
    // Host globals are back at once; window-sourced ones (Text) linger so a
    // straggling guest continuation resolves them instead of throwing
    // "Text is not defined" (v4.5.2 field report from feilin005.js).
    expect(Object.getOwnPropertyDescriptor(g, "atob")?.get).toBeUndefined();
    expect(Object.getOwnPropertyDescriptor(g, "Text")?.get).toBeDefined();
    expect(g.Text).toBe(w.Text);
    // Real elapsed time is the mechanism under test: the tombstone is a
    // wall-clock grace period scheduled on the pristine host setTimeout.
    await Bun.sleep(70);
    expect(g.Text).toBeUndefined();
    expect(Object.getOwnPropertyDescriptor(g, "Text")?.get).toBeUndefined();
    expect(g.navigator).toBe(hostNavigator);
  });

  test("an expired tombstone leaves callable stubs, never a ReferenceError", async () => {
    // The grace period ends, but guest stragglers can still be running: the
    // FeiLin heartbeat `tE` re-arms itself every 2s and dereferences `moveBy`
    // (feilin008.js:169658). A hard `delete` turned that read into an
    // uncaught ReferenceError — fatal in the host realm, and the field crash
    // this guards. The name must stay resolvable and callable.
    const { g, w } = makeSandbox();
    (w as Record<string, unknown>).moveBy = () => {};
    installGlobalWindowAlias(g, w, 15);
    removeGlobalWindowAlias(g, w);
    // Real elapsed time is the mechanism under test: the tombstone is a
    // wall-clock grace period armed on the pristine host setTimeout.
    await Bun.sleep(70);
    expect(typeof g.moveBy).toBe("function");
    expect(() => (g.moveBy as () => void)()).not.toThrow();
    // The stub must not keep the closed window reachable from globalThis.
    expect(g.moveBy).not.toBe((w as Record<string, unknown>).moveBy);
  });

  test("a new install cancels the pending tombstone", async () => {
    const { g, w } = makeSandbox();
    const w2: Record<string, unknown> = {
      Text: class FakeText2 {},
      atob: (s: string) => `win2-atob(${s})`,
      navigator: { userAgent: "window2" },
    };
    installGlobalWindowAlias(g, w, 15);
    removeGlobalWindowAlias(g, w);
    installGlobalWindowAlias(g, w2, 15); // new wave inside the grace period
    await Bun.sleep(70);
    expect(g.Text).toBe(w2.Text); // first tombstone aborted
    removeGlobalWindowAlias(g, w2);
    // The SECOND wave's tombstone owns the cleanup: this overlap is where
    // stale-accessor laundering used to pin the first closed window forever.
    await Bun.sleep(70);
    expect(g.Text).toBeUndefined();
    expect(g.window).toBeUndefined();
  });

  test("an expired tombstone leaves callable stubs, never a ReferenceError", async () => {
    // The grace period ends, but guest stragglers can still be running: the
    // FeiLin heartbeat `tE` re-arms itself every 2s and dereferences `moveBy`
    // (feilin008.js:169658). A hard `delete` turned that read into an uncaught
    // ReferenceError — fatal in the host realm, and the field crash this
    // guards. The name must stay resolvable and callable.
    const { g, w } = makeSandbox();
    (w as Record<string, unknown>).moveBy = () => {};
    installGlobalWindowAlias(g, w, 15);
    removeGlobalWindowAlias(g, w);
    await Bun.sleep(70);
    expect(typeof g.moveBy).toBe("function");
    expect(() => (g.moveBy as () => void)()).not.toThrow();
    // The stub must not keep the closed window reachable from globalThis.
    expect(g.moveBy).not.toBe((w as Record<string, unknown>).moveBy);
  });

  test("requestAnimationFrame/cancelAnimationFrame resolve during a solve", () => {
    // Bun has no native rAF. While these sat in HOST_CRITICAL_GLOBALS the
    // alias pass skipped them, so the FeiLin bundle's 9 bare
    // `requestAnimationFrame` references (only one `typeof`-guarded) were
    // unresolvable — silent fingerprint degradation, visible only as a lower
    // solve rate.
    const g: Record<string, unknown> = {};
    const w: Record<string, unknown> = {
      requestAnimationFrame: () => 1,
      cancelAnimationFrame: () => {},
    };
    installGlobalWindowAlias(g, w, 15);
    try {
      expect(typeof g.requestAnimationFrame).toBe("function");
      expect(typeof g.cancelAnimationFrame).toBe("function");
    } finally {
      removeGlobalWindowAlias(g, w);
    }
  });
});

// Memory guards for long-running serve processes (issue #50: monotonic RSS
// growth, 2.9 days → 9.95GB). Every structure here is module-scoped and shared
// across solves, so without an explicit bound each one grows for the process
// lifetime.
describe("memory guards (issue #50)", () => {
  test("guest request log is a ring buffer, not an append-only array", () => {
    const cap = __captchaMemStats().requestLogCap;
    const beyond = cap + 44;
    for (let i = 0; i < beyond; i++) {
      noteRequest({ at: Date.now(), method: "GET", url: `https://example.com/${i}` });
    }
    const stats = __captchaMemStats();
    expect(stats.requestLogLength).toBe(cap);
  });

  test("in-memory CDN cache evicts oldest entries at the cap (pe rotation)", () => {
    for (let i = 0; i < 20; i++) {
      rememberCdnBody(`https://o.alicdn.com/dynamicJS/v/pe.${1000 + i}.js`, Buffer.from("x"));
    }
    expect(__captchaMemStats().cdnCacheSize).toBe(__captchaMemStats().cdnCacheCap);
  });

  test("heap reclaim runs at most once per throttle window", () => {
    const saved = process.env.CAPTCHA_GC_MIN_INTERVAL_MS;
    try {
      const before = __captchaMemStats().gcCalls;
      process.env.CAPTCHA_GC_MIN_INTERVAL_MS = "0";
      reclaimCaptchaHeap();
      reclaimCaptchaHeap();
      expect(__captchaMemStats().gcCalls).toBe(before + 2);

      process.env.CAPTCHA_GC_MIN_INTERVAL_MS = "3600000";
      reclaimCaptchaHeap();
      expect(__captchaMemStats().gcCalls).toBe(before + 2);
    } finally {
      if (saved === undefined) delete process.env.CAPTCHA_GC_MIN_INTERVAL_MS;
      else process.env.CAPTCHA_GC_MIN_INTERVAL_MS = saved;
    }
  });

  test("reused-window solve budget defaults to the reduced cap", () => {
    // 25 → 8 (issue #50): each solve leaves SDK instance graphs resident in a
    // reused window, so the cap bounds a generation's retention peak.
    if (process.env.CAPTCHA_REUSE_MAX_SOLVES === undefined) {
      expect(__captchaMemStats().reuseMaxSolves).toBe(8);
    }
  });
});
