/**
 * Build-time official plugin-MCP catalogue (sidecar asset, inlined into the
 * single-file binary via the json import attribute — same pattern as
 * `src/proxy/zcode_system.json`).
 *
 * Regenerated by `scripts/regen-mcp-catalogue.ts` when ZCode ships plugins;
 * the runtime NEVER fetches the marketplace. Shape is validated at load so a
 * drifted artifact fails loudly at startup instead of serving broken routes.
 *
 * @see _reverse/NOTEPAD.md "Official plugin MCP"
 */
import raw from "./official-catalogue.json" with { type: "json" };

export interface OfficialMcpServerDef {
  /** mcpServers key from the plugin's .mcp.json — the /mcp/{key} route name. */
  key: string;
  /** Gateway route identifier (path segment after /api/v1/mcp/server/). */
  routeId: string;
  /** Upstream path (`/api/v1/mcp/server/{routeId}`), pre-origin. */
  path: string;
  plugin: string;
  version: string;
  marketplace: string;
  requiresPaidPlan: boolean;
  displayName: Record<string, string>;
  description: Record<string, string>;
  category?: string;
}

export interface OfficialMcpCatalogue {
  generatedAt: string;
  marketplaceUrl: string;
  defaultUpstreamOrigin: string;
  servers: OfficialMcpServerDef[];
}

interface RawServer {
  key?: unknown;
  routeId?: unknown;
  path?: unknown;
  plugin?: unknown;
  version?: unknown;
  marketplace?: unknown;
  requiresPaidPlan?: unknown;
  displayName?: unknown;
  description?: unknown;
  category?: unknown;
}

function expectString(v: unknown, field: string): string {
  if (typeof v !== "string" || v.length === 0) {
    throw new Error(`official-catalogue.json: field "${field}" must be a non-empty string (regen with scripts/regen-mcp-catalogue.ts)`);
  }
  return v;
}

function expectStringMap(v: unknown, field: string): Record<string, string> {
  if (typeof v !== "object" || v === null) {
    throw new Error(`official-catalogue.json: field "${field}" must be an object`);
  }
  const out: Record<string, string> = {};
  for (const [k, val] of Object.entries(v as Record<string, unknown>)) {
    if (typeof val !== "string") {
      throw new Error(`official-catalogue.json: field "${field}.${k}" must be a string`);
    }
    out[k] = val;
  }
  return out;
}

function parseServer(entry: RawServer, index: number): OfficialMcpServerDef {
  const at = `servers[${index}]`;
  const def: OfficialMcpServerDef = {
    key: expectString(entry.key, `${at}.key`),
    routeId: expectString(entry.routeId, `${at}.routeId`),
    path: expectString(entry.path, `${at}.path`),
    plugin: expectString(entry.plugin, `${at}.plugin`),
    version: expectString(entry.version, `${at}.version`),
    marketplace: expectString(entry.marketplace, `${at}.marketplace`),
    requiresPaidPlan: entry.requiresPaidPlan === true,
    displayName: expectStringMap(entry.displayName, `${at}.displayName`),
    description: expectStringMap(entry.description, `${at}.description`),
  };
  if (entry.category !== undefined) def.category = expectString(entry.category, `${at}.category`);
  if (!def.path.startsWith("/api/v1/mcp/server/") || def.path !== `/api/v1/mcp/server/${def.routeId}`) {
    throw new Error(`official-catalogue.json: ${at}.path "${def.path}" is not the canonical /api/v1/mcp/server/{routeId} form`);
  }
  return def;
}

const rawServers = (raw as { servers?: unknown }).servers;
if (!Array.isArray(rawServers)) {
  throw new Error("official-catalogue.json: \"servers\" must be an array (regen with scripts/regen-mcp-catalogue.ts)");
}
const servers = rawServers.map((s, index) => parseServer(s as RawServer, index));

export const OFFICIAL_MCP_CATALOGUE: OfficialMcpCatalogue = {
  generatedAt: expectString((raw as { generatedAt?: unknown }).generatedAt, "generatedAt"),
  marketplaceUrl: expectString((raw as { marketplaceUrl?: unknown }).marketplaceUrl, "marketplaceUrl"),
  defaultUpstreamOrigin: expectString((raw as { defaultUpstreamOrigin?: unknown }).defaultUpstreamOrigin, "defaultUpstreamOrigin"),
  servers,
};

const byKey = new Map(servers.map((s) => [s.key, s]));

export function lookupOfficialMcpServer(key: string): OfficialMcpServerDef | undefined {
  return byKey.get(key);
}
